[package]
name = "mitra"
version = "0.1.0"
description = "Your tiny open-source desktop companion."
authors = ["you"]
edition = "2021"

[lib]
name = "mitra_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.39.6"
win-gsmtc = "0.1.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
